//<script><?php restricted(''); ?>

$(document).ready(function() {
	debug('LOAD: <?php echo $path; ?>');
});

function OpenQuestions(event_id) {

	var QUESTIONS_COLUMNS = [
		{ data: 'cts_questions.q01', title: 'Field 1', sClass: 'exportable' },
		{ data: 'cts_questions.q02', title: 'Field 2', sClass: 'exportable' },
		{ data: 'cts_questions.q03', title: 'Field 3', sClass: 'exportable' },
		{ data: 'cts_questions.q04', title: 'Field 4', sClass: 'exportable' },
		{ data: 'cts_questions.q05', title: 'Field 5', sClass: 'exportable' },
		{ data: 'cts_questions.q06', title: 'Field 6', sClass: 'exportable' },
		{ data: 'cts_questions.q07', title: 'Field 7', sClass: 'exportable' },
		{ data: 'cts_questions.q08', title: 'Field 8', sClass: 'exportable' },
		{ data: 'cts_questions.q09', title: 'Field 9', sClass: 'exportable' },
		{ data: 'cts_questions.q10', title: 'Field 10', sClass: 'exportable' },
		{ data: 'cts_questions.q11', title: 'Field 11', sClass: 'exportable' },
		{ data: 'cts_questions.q12', title: 'Field 12', sClass: 'exportable' },
		{ data: 'cts_questions.q13', title: 'Field 13', sClass: 'exportable' },
		{ data: 'cts_questions.q14', title: 'Field 14', sClass: 'exportable' },
		{ data: 'cts_questions.q15', title: 'Field 15', sClass: 'exportable' },
		{ data: 'cts_questions.q16', title: 'Field 16', sClass: 'exportable' },
		{ data: 'cts_questions.q17', title: 'Field 17', sClass: 'exportable' },
		{ data: 'cts_questions.q18', title: 'Field 18', sClass: 'exportable' },
		{ data: 'cts_questions.q19', title: 'Field 19', sClass: 'exportable' },
		{ data: 'cts_questions.q20', title: 'Field 20', sClass: 'exportable' },
		{ data: 'cts_questions.q21', title: 'Field 21', sClass: 'exportable' },
		{ data: 'cts_questions.q22', title: 'Field 22', sClass: 'exportable' },
		{ data: 'cts_questions.q23', title: 'Field 23', sClass: 'exportable' },
		{ data: 'cts_questions.q24', title: 'Field 24', sClass: 'exportable' },
		{ data: 'cts_questions.q25', title: 'Field 25', sClass: 'exportable' },
		{ data: 'cts_questions.q26', title: 'Field 26', sClass: 'exportable' },
		{ data: 'cts_questions.q27', title: 'Field 27', sClass: 'exportable' },
		{ data: 'cts_questions.q28', title: 'Field 28', sClass: 'exportable' },
		{ data: 'cts_questions.q29', title: 'Field 29', sClass: 'exportable' },
		{ data: 'cts_questions.q30', title: 'Field 30', sClass: 'exportable' },
		
		{ data: 'cts_questions.q31', title: 'Field 31', sClass: 'exportable' },
		{ data: 'cts_questions.q32', title: 'Field 32', sClass: 'exportable' },
		{ data: 'cts_questions.q33', title: 'Field 33', sClass: 'exportable' },
		{ data: 'cts_questions.q34', title: 'Field 34', sClass: 'exportable' },
		{ data: 'cts_questions.q35', title: 'Field 35', sClass: 'exportable' },
		{ data: 'cts_questions.q36', title: 'Field 36', sClass: 'exportable' },
		{ data: 'cts_questions.q37', title: 'Field 37', sClass: 'exportable' },
		{ data: 'cts_questions.q38', title: 'Field 38', sClass: 'exportable' },
		{ data: 'cts_questions.q39', title: 'Field 39', sClass: 'exportable' },
		{ data: 'cts_questions.q40', title: 'Field 40', sClass: 'exportable' },
		
		{ data: 'cts_questions.q41', title: 'Field 41', sClass: 'exportable' },
		{ data: 'cts_questions.q42', title: 'Field 42', sClass: 'exportable' },
		{ data: 'cts_questions.q43', title: 'Field 43', sClass: 'exportable' },
		{ data: 'cts_questions.q44', title: 'Field 44', sClass: 'exportable' },
		{ data: 'cts_questions.q45', title: 'Field 45', sClass: 'exportable' },
		{ data: 'cts_questions.q46', title: 'Field 46', sClass: 'exportable' },
		{ data: 'cts_questions.q47', title: 'Field 47', sClass: 'exportable' },
		{ data: 'cts_questions.q48', title: 'Field 48', sClass: 'exportable' },
		{ data: 'cts_questions.q49', title: 'Field 49', sClass: 'exportable' },
		{ data: 'cts_questions.q50', title: 'Field 50', sClass: 'exportable' },
		
		{ data: 'cts_questions.q51', title: 'Field 51', sClass: 'exportable' },
		{ data: 'cts_questions.q52', title: 'Field 52', sClass: 'exportable' },
		{ data: 'cts_questions.q53', title: 'Field 53', sClass: 'exportable' },
		{ data: 'cts_questions.q54', title: 'Field 54', sClass: 'exportable' },
		{ data: 'cts_questions.q55', title: 'Field 55', sClass: 'exportable' },
		{ data: 'cts_questions.q56', title: 'Field 56', sClass: 'exportable' },
		{ data: 'cts_questions.q57', title: 'Field 57', sClass: 'exportable' },
		{ data: 'cts_questions.q58', title: 'Field 58', sClass: 'exportable' },
		{ data: 'cts_questions.q59', title: 'Field 59', sClass: 'exportable' },
		{ data: 'cts_questions.q60', title: 'Field 60', sClass: 'exportable' },
		
		{ data: 'cts_questions.q61', title: 'Field 61', sClass: 'exportable' },
		{ data: 'cts_questions.q62', title: 'Field 62', sClass: 'exportable' },
		{ data: 'cts_questions.q63', title: 'Field 63', sClass: 'exportable' },
		{ data: 'cts_questions.q64', title: 'Field 64', sClass: 'exportable' },
		{ data: 'cts_questions.q65', title: 'Field 65', sClass: 'exportable' },
		{ data: 'cts_questions.q66', title: 'Field 66', sClass: 'exportable' },
		{ data: 'cts_questions.q67', title: 'Field 67', sClass: 'exportable' },
		{ data: 'cts_questions.q68', title: 'Field 68', sClass: 'exportable' },
		{ data: 'cts_questions.q69', title: 'Field 69', sClass: 'exportable' },
		{ data: 'cts_questions.q70', title: 'Field 70', sClass: 'exportable' },
		
		{ data: 'cts_questions.q71', title: 'Field 71', sClass: 'exportable' },
		{ data: 'cts_questions.q72', title: 'Field 72', sClass: 'exportable' },
		{ data: 'cts_questions.q73', title: 'Field 73', sClass: 'exportable' },
		{ data: 'cts_questions.q74', title: 'Field 74', sClass: 'exportable' },
		{ data: 'cts_questions.q75', title: 'Field 75', sClass: 'exportable' },
		{ data: 'cts_questions.q76', title: 'Field 76', sClass: 'exportable' },
		{ data: 'cts_questions.q77', title: 'Field 77', sClass: 'exportable' },
		{ data: 'cts_questions.q78', title: 'Field 78', sClass: 'exportable' },
		{ data: 'cts_questions.q79', title: 'Field 79', sClass: 'exportable' },
		{ data: 'cts_questions.q80', title: 'Field 80', sClass: 'exportable' },
		
		{ data: 'cts_questions.q81', title: 'Field 81', sClass: 'exportable' },
		{ data: 'cts_questions.q82', title: 'Field 82', sClass: 'exportable' },
		{ data: 'cts_questions.q83', title: 'Field 83', sClass: 'exportable' },
		{ data: 'cts_questions.q84', title: 'Field 84', sClass: 'exportable' },
		{ data: 'cts_questions.q85', title: 'Field 85', sClass: 'exportable' },
		{ data: 'cts_questions.q86', title: 'Field 86', sClass: 'exportable' },
		{ data: 'cts_questions.q87', title: 'Field 87', sClass: 'exportable' },
		{ data: 'cts_questions.q88', title: 'Field 88', sClass: 'exportable' },
		{ data: 'cts_questions.q89', title: 'Field 89', sClass: 'exportable' },
		{ data: 'cts_questions.q90', title: 'Field 90', sClass: 'exportable' },
		
		{ data: 'cts_questions.q91', title: 'Field 91', sClass: 'exportable' },
		{ data: 'cts_questions.q92', title: 'Field 92', sClass: 'exportable' },
		{ data: 'cts_questions.q93', title: 'Field 93', sClass: 'exportable' },
		{ data: 'cts_questions.q94', title: 'Field 94', sClass: 'exportable' },
		{ data: 'cts_questions.q95', title: 'Field 95', sClass: 'exportable' },
		{ data: 'cts_questions.q96', title: 'Field 96', sClass: 'exportable' },
		{ data: 'cts_questions.q97', title: 'Field 97', sClass: 'exportable' },
		{ data: 'cts_questions.q98', title: 'Field 98', sClass: 'exportable' },
		{ data: 'cts_questions.q99', title: 'Field 99', sClass: 'exportable' },
		{ data: 'cts_questions.q100', title: 'Field 100', sClass: 'exportable' },
		
		{ data: 'cts_questions.q101', title: 'Field 101', sClass: 'exportable' },
		{ data: 'cts_questions.q102', title: 'Field 102', sClass: 'exportable' },
		{ data: 'cts_questions.q103', title: 'Field 103', sClass: 'exportable' },
		{ data: 'cts_questions.q104', title: 'Field 104', sClass: 'exportable' },
		{ data: 'cts_questions.q105', title: 'Field 105', sClass: 'exportable' },
		{ data: 'cts_questions.q106', title: 'Field 106', sClass: 'exportable' },
		{ data: 'cts_questions.q107', title: 'Field 107', sClass: 'exportable' },
		{ data: 'cts_questions.q108', title: 'Field 108', sClass: 'exportable' },
		{ data: 'cts_questions.q109', title: 'Field 109', sClass: 'exportable' },
		{ data: 'cts_questions.q110', title: 'Field 110', sClass: 'exportable' },
		{ data: 'cts_questions.q111', title: 'Field 111', sClass: 'exportable' },
		{ data: 'cts_questions.q112', title: 'Field 112', sClass: 'exportable' },
		{ data: 'cts_questions.q113', title: 'Field 113', sClass: 'exportable' },
		{ data: 'cts_questions.q114', title: 'Field 114', sClass: 'exportable' },
		{ data: 'cts_questions.q115', title: 'Field 115', sClass: 'exportable' },
		{ data: 'cts_questions.q116', title: 'Field 116', sClass: 'exportable' },
		{ data: 'cts_questions.q117', title: 'Field 117', sClass: 'exportable' },
		{ data: 'cts_questions.q118', title: 'Field 118', sClass: 'exportable' },
		{ data: 'cts_questions.q119', title: 'Field 119', sClass: 'exportable' },
		{ data: 'cts_questions.q120', title: 'Field 120', sClass: 'exportable' },
	];

	
	
	var Questions;
		
	var Questions_CONTAINER_SELECTOR = '#questions-editor';
	var Questions_Config = {
		CONTAINER_SELECTOR: Questions_CONTAINER_SELECTOR,

		EDITOR_CONFIG: {
			ajax: { url: '/contest/dashboard/get_questions/'+event_id, type: 'POST' },
			table: Questions_CONTAINER_SELECTOR,
			template: '#questions-form',
			fields: [
				{
					label: 'Min',
					name: 'cts_questions.score_min',
					attr: {
						type: 'number',
					}
				},
				{
					label: 'Max',
					name: 'cts_questions.score_max',
					attr: {
						type: 'number',
					}
				},
				{
					label: 'Step',
					name: 'cts_questions.score_step',
					attr: {
						type: 'number',
					}
				},
				{ label: 'Field 1',  name: 'cts_questions.q01_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 2',  name: 'cts_questions.q02_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 3',  name: 'cts_questions.q03_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 4',  name: 'cts_questions.q04_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 5',  name: 'cts_questions.q05_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 6',  name: 'cts_questions.q06_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 7',  name: 'cts_questions.q07_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 8',  name: 'cts_questions.q08_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 9',  name: 'cts_questions.q09_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 10', name: 'cts_questions.q10_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 11', name: 'cts_questions.q11_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 12', name: 'cts_questions.q12_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 13', name: 'cts_questions.q13_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 14', name: 'cts_questions.q14_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 15', name: 'cts_questions.q15_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 16', name: 'cts_questions.q16_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 17', name: 'cts_questions.q17_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 18', name: 'cts_questions.q18_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 19', name: 'cts_questions.q19_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 20', name: 'cts_questions.q20_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 21', name: 'cts_questions.q21_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 22', name: 'cts_questions.q22_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 23', name: 'cts_questions.q23_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 24', name: 'cts_questions.q24_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 25', name: 'cts_questions.q25_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 26', name: 'cts_questions.q26_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 27', name: 'cts_questions.q27_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 28', name: 'cts_questions.q28_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 29', name: 'cts_questions.q29_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 30', name: 'cts_questions.q30_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				
				{ label: 'Field 31', name: 'cts_questions.q31_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 32', name: 'cts_questions.q32_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 33', name: 'cts_questions.q33_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 34', name: 'cts_questions.q34_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 35', name: 'cts_questions.q35_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 36', name: 'cts_questions.q36_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 37', name: 'cts_questions.q37_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 38', name: 'cts_questions.q38_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 39', name: 'cts_questions.q39_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 40', name: 'cts_questions.q40_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				
				{ label: 'Field 41', name: 'cts_questions.q41_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 42', name: 'cts_questions.q42_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 43', name: 'cts_questions.q43_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 44', name: 'cts_questions.q44_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 45', name: 'cts_questions.q45_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 46', name: 'cts_questions.q46_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 47', name: 'cts_questions.q47_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 48', name: 'cts_questions.q48_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 49', name: 'cts_questions.q49_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 50', name: 'cts_questions.q50_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				
				{ label: 'Field 51', name: 'cts_questions.q51_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 52', name: 'cts_questions.q52_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 53', name: 'cts_questions.q53_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 54', name: 'cts_questions.q54_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 55', name: 'cts_questions.q55_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 56', name: 'cts_questions.q56_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 57', name: 'cts_questions.q57_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 58', name: 'cts_questions.q58_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 59', name: 'cts_questions.q59_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 60', name: 'cts_questions.q60_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				
				{ label: 'Field 61', name: 'cts_questions.q61_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 62', name: 'cts_questions.q62_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 63', name: 'cts_questions.q63_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 64', name: 'cts_questions.q64_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 65', name: 'cts_questions.q65_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 66', name: 'cts_questions.q66_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 67', name: 'cts_questions.q67_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 68', name: 'cts_questions.q68_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 69', name: 'cts_questions.q69_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 70', name: 'cts_questions.q70_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				
				{ label: 'Field 71', name: 'cts_questions.q71_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 72', name: 'cts_questions.q72_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 73', name: 'cts_questions.q73_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 74', name: 'cts_questions.q74_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 75', name: 'cts_questions.q75_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 76', name: 'cts_questions.q76_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 77', name: 'cts_questions.q77_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 78', name: 'cts_questions.q78_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 79', name: 'cts_questions.q79_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 80', name: 'cts_questions.q80_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				
				{ label: 'Field 81', name: 'cts_questions.q81_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 82', name: 'cts_questions.q82_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 83', name: 'cts_questions.q83_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 84', name: 'cts_questions.q84_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 85', name: 'cts_questions.q85_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 86', name: 'cts_questions.q86_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 87', name: 'cts_questions.q87_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 88', name: 'cts_questions.q88_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 89', name: 'cts_questions.q89_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 90', name: 'cts_questions.q90_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				
				{ label: 'Field 91', name: 'cts_questions.q91_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 92', name: 'cts_questions.q92_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 93', name: 'cts_questions.q93_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 94', name: 'cts_questions.q94_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 95', name: 'cts_questions.q95_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 96', name: 'cts_questions.q96_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 97', name: 'cts_questions.q97_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 98', name: 'cts_questions.q98_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 99', name: 'cts_questions.q99_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				
				{ label: 'Field 100', name: 'cts_questions.q100_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 101', name: 'cts_questions.q101_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 102', name: 'cts_questions.q102_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 103', name: 'cts_questions.q103_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 104', name: 'cts_questions.q104_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 105', name: 'cts_questions.q105_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 106', name: 'cts_questions.q106_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 107', name: 'cts_questions.q107_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 108', name: 'cts_questions.q108_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 109', name: 'cts_questions.q109_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 110', name: 'cts_questions.q110_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 111', name: 'cts_questions.q111_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 112', name: 'cts_questions.q112_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 113', name: 'cts_questions.q113_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 114', name: 'cts_questions.q114_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 115', name: 'cts_questions.q115_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 116', name: 'cts_questions.q116_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 117', name: 'cts_questions.q117_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 118', name: 'cts_questions.q118_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 119', name: 'cts_questions.q119_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				{ label: 'Field 120', name: 'cts_questions.q120_scoring', type:  "checkbox", options: [ { label: 'Enable scoring', value: 1 } ], def: 0, separator: "," },
				
			],
		},

		DATATABLE_CONFIG: {
			editTitle: 'Edit Question',
			ajax: { url: '/contest/dashboard/get_questions/'+event_id, type: 'POST' },
			order: [[ 2, 'asc' ]],
			scroller: true,
			responsive: true,
			columns: QUESTIONS_COLUMNS,
			canCreate: false,
		},
		
	};
	
	Questions = InitDatatableEditor( Questions_Config );
		
}

